services:
  data-extraction-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8090/ping/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - expnet
  
  tika-ocr:
    build:
      context: .
      dockerfile: Dockerfile.ocr
    ports:
      - "8093:8091"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - ./tika-config.xml:/app/tika-config.xml:ro
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8091/ping/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - expnet

networks:
  expnet:
    name: expnet