---
agents:
  provider: "gcp"
  machineType: "n1-standard-8"
  useVault: true

steps:
  - label: ":whale: Build docker image"
    command: "scripts/build-and-publish-docker-image.sh"

steps:
  - label: ":pytest: e2e tests"
    command: "make e2e"
