---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

agents:
  image: "docker.elastic.co/ci-agent-images/drivah:0.27.1@sha256:840a528e45c7c2508d6bba1cbe4fc49135ddb63a5fa19e6f778cdb6521069825"

steps:
  - label: ":whale: Build docker image"
    command: "scripts/build-and-publish-docker-image.sh"
