---
agents:
  provider: "gcp"
  machineType: "n1-standard-8"
  useVault: true
  image: "docker.elastic.co/ci-agent-images/drivah:0.18.1"

steps:
  - label: ":whale: Build docker image"
    command: "scripts/build-and-publish-docker-image.sh"

steps:
  - label: ":pytest: e2e tests"
    command: "make e2e"
