---
agents:
  provider: "gcp"
  machineType: "n1-standard-2"
  useVault: true
  image: family/enterprise-search-ubuntu-2204-connectors-py

steps:
  - label: ":whale: Build docker image"
    command: "scripts/build-and-publish-docker-image.sh"

steps:
  - label: ":pytest: e2e tests"
    command: "make e2e"
