---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

agents:
  provider: "gcp"

steps:
  - label: ":whale::hammer: Build docker image"
    command: "scripts/build-docker-image.sh"
  - wait
  - label: ":whale::rocket: Publish docker image"
    command: "scripts/publish-docker-image.sh"
