---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

agents:
  provider: "gcp"
  machineType: "n1-standard-8"
  useVault: false

steps:
  - command:
    - ".buildkite/run_dockerized_test.sh"

steps:
  - label: ":whale: Build docker image"
    command: "scripts/build-and-publish-docker-image.sh"

steps:
  - label: ":pytest: e2e tests"
  - command:
    - ".buildkite/run_dockerized_test.sh"
